"""Add courts and games functionality

Revision ID: 0ae1342b4145
Revises: c061d883bec0
Create Date: 2025-09-17 00:11:43.320522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae1342b4145'
down_revision = 'c061d883bec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('courts', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
