"""Add stats and ratings models

Revision ID: 37e8162690e7
Revises: 0ae1342b4145
Create Date: 2025-10-06 16:50:48.415570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e8162690e7'
down_revision = '0ae1342b4145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('to_user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('unique_game_user_rating', ['from_user_id', 'to_user_id', 'game_id'])
        batch_op.drop_constraint(batch_op.f('player_ratings_from_user_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('player_ratings_to_user_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['to_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['from_user_id'], ['id'])
        batch_op.drop_column('from_user')
        batch_op.drop_column('to_user')
        batch_op.drop_column('score')

    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('unique_game_user_stats', ['game_id', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.drop_constraint('unique_game_user_stats', type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('player_ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('to_user', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('from_user', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('player_ratings_to_user_fkey'), 'users', ['to_user'], ['id'])
        batch_op.create_foreign_key(batch_op.f('player_ratings_from_user_fkey'), 'users', ['from_user'], ['id'])
        batch_op.drop_constraint('unique_game_user_rating', type_='unique')
        batch_op.drop_column('rating')
        batch_op.drop_column('to_user_id')
        batch_op.drop_column('from_user_id')

    # ### end Alembic commands ###
